// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing-pages/BrutalMono.tsx": () => import("../components/mockups/landing-pages/BrutalMono.tsx"),
  "./components/mockups/landing-pages/DeepVault.tsx": () => import("../components/mockups/landing-pages/DeepVault.tsx"),
  "./components/mockups/landing-pages/SteelEdge.tsx": () => import("../components/mockups/landing-pages/SteelEdge.tsx")
};
